"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var Countries = /** @class */ (function () {
    function Countries() {
        this.countries = [
            { key: 'AF', title: "Afghanistan" },
            { key: 'AL', title: "Albania" },
            { key: 'DZ', title: "Algeria" },
            { key: 'AS', title: "American Samoa" },
            { key: 'AD', title: "Andorra" },
            { key: 'AO', title: "Angola" },
            { key: 'AI', title: "Anguilla" },
            { key: 'AQ', title: "Antarctica" },
            { key: 'AG', title: "Antigua and Barbuda" },
            { key: 'AR', title: "Argentina" },
            { key: 'AM', title: "Armenia" },
            { key: 'AW', title: "Aruba" },
            { key: 'AU', title: "Australia" },
            { key: 'AT', title: "Austria" },
            { key: 'AZ', title: "Azerbaijan" },
            { key: 'BS', title: "Bahamas" },
            { key: 'BH', title: "Bahrain" },
            { key: 'BD', title: "Bangladesh" },
            { key: 'BB', title: "Barbados" },
            { key: 'BY', title: "Belarus" },
            { key: 'BE', title: "Belgium" },
            { key: 'BZ', title: "Belize" },
            { key: 'BJ', title: "Benin" },
            { key: 'BM', title: "Bermuda" },
            { key: 'BT', title: "Bhutan" },
            { key: 'BO', title: "Bolivia" },
            { key: 'BA', title: "Bosnia and Herzegowina" },
            { key: 'BW', title: "Botswana" },
            { key: 'BV', title: "Bouvet Island" },
            { key: 'BR', title: "Brazil" },
            { key: 'IO', title: "British Indian Ocean Territory" },
            { key: 'BN', title: "Brunei Darussalam" },
            { key: 'BG', title: "Bulgaria" },
            { key: 'BF', title: "Burkina Faso" },
            { key: 'BI', title: "Burundi" },
            { key: 'KH', title: "Cambodia" },
            { key: 'CM', title: "Cameroon" },
            { key: 'CA', title: "Canada" },
            { key: 'CV', title: "Cape Verde" },
            { key: 'KY', title: "Cayman Islands" },
            { key: 'CF', title: "Central African Republic" },
            { key: 'TD', title: "Chad" },
            { key: 'CL', title: "Chile" },
            { key: 'CN', title: "China" },
            { key: 'CX', title: "Christmas Island" },
            { key: 'CC', title: "Cocos (Keeling) Islands" },
            { key: 'CO', title: "Colombia" },
            { key: 'KM', title: "Comoros" },
            { key: 'CG', title: "Congo" },
            { key: 'CK', title: "Cook Islands" },
            { key: 'CR', title: "Costa Rica" },
            { key: 'CI', title: "Cote D'ivoire" },
            { key: 'HR', title: "Croatia (Hrvatska)" },
            { key: 'CY', title: "Cyprus" },
            { key: 'CZ', title: "Czech Republic" },
            { key: 'DK', title: "Denmark" },
            { key: 'DJ', title: "Djibouti" },
            { key: 'DM', title: "Dominica" },
            { key: 'DO', title: "Dominican Republic" },
            { key: 'TP', title: "East Timor" },
            { key: 'EC', title: "Ecuador" },
            { key: 'EG', title: "Egypt" },
            { key: 'SV', title: "El Salvador" },
            { key: 'GQ', title: "Equatorial Guinea" },
            { key: 'ER', title: "Eritrea" },
            { key: 'EE', title: "Estonia" },
            { key: 'ET', title: "Ethiopia" },
            { key: 'FK', title: "Falkland Islands (Malvinas)" },
            { key: 'FO', title: "Faroe Islands" },
            { key: 'FJ', title: "Fiji" },
            { key: 'FI', title: "Finland" },
            { key: 'FR', title: "France" },
            { key: 'FX', title: "France, Metropolitan" },
            { key: 'GF', title: "French Guiana" },
            { key: 'PF', title: "French Polynesia" },
            { key: 'TF', title: "French Southern Territories" },
            { key: 'GA', title: "Gabon" },
            { key: 'GM', title: "Gambia" },
            { key: 'GE', title: "Georgia" },
            { key: 'DE', title: "Germany" },
            { key: 'GH', title: "Ghana" },
            { key: 'GI', title: "Gibraltar" },
            { key: 'GR', title: "Greece" },
            { key: 'GL', title: "Greenland" },
            { key: 'GD', title: "Grenada" },
            { key: 'GP', title: "Guadeloupe" },
            { key: 'GU', title: "Guam" },
            { key: 'GT', title: "Guatemala" },
            { key: 'GN', title: "Guinea" },
            { key: 'GW', title: "Guinea-bissau" },
            { key: 'GY', title: "Guyana" },
            { key: 'HT', title: "Haiti" },
            { key: 'HM', title: "Heard and McDonald Islands" },
            { key: 'HN', title: "Honduras" },
            { key: 'HK', title: "Hong Kong" },
            { key: 'HU', title: "Hungary" },
            { key: 'IS', title: "Iceland" },
            { key: 'IN', title: "India" },
            { key: 'ID', title: "Indonesia" },
            { key: 'IQ', title: "Iraq" },
            { key: 'IE', title: "Ireland" },
            { key: 'IL', title: "Israel" },
            { key: 'IT', title: "Italy" },
            { key: 'JM', title: "Jamaica" },
            { key: 'JP', title: "Japan" },
            { key: 'JO', title: "Jordan" },
            { key: 'KZ', title: "Kazakhstan" },
            { key: 'KE', title: "Kenya" },
            { key: 'KI', title: "Kiribati" },
            { key: 'KR', title: "Korea, Republic of" },
            { key: 'KW', title: "Kuwait" },
            { key: 'KG', title: "Kyrgyzstan" },
            { key: 'LA', title: "Lao People's Democratic Republic" },
            { key: 'LV', title: "Latvia" },
            { key: 'LB', title: "Lebanon" },
            { key: 'LS', title: "Lesotho" },
            { key: 'LR', title: "Liberia" },
            { key: 'LY', title: "Libyan Arab Jamahiriya" },
            { key: 'LI', title: "Liechtenstein" },
            { key: 'LT', title: "Lithuania" },
            { key: 'LU', title: "Luxembourg" },
            { key: 'MO', title: "Macau" },
            { key: 'MK', title: "Macedonia" },
            { key: 'MG', title: "Madagascar" },
            { key: 'MW', title: "Malawi" },
            { key: 'MY', title: "Malaysia" },
            { key: 'MV', title: "Maldives" },
            { key: 'ML', title: "Mali" },
            { key: 'MT', title: "Malta" },
            { key: 'MH', title: "Marshall Islands" },
            { key: 'MQ', title: "Martinique" },
            { key: 'MR', title: "Mauritania" },
            { key: 'MU', title: "Mauritius" },
            { key: 'YT', title: "Mayotte" },
            { key: 'MX', title: "Mexico" },
            { key: 'FM', title: "Micronesia, Federated States of" },
            { key: 'MD', title: "Moldova, Republic of" },
            { key: 'MC', title: "Monaco" },
            { key: 'MN', title: "Mongolia" },
            { key: 'MS', title: "Montserrat" },
            { key: 'MA', title: "Morocco" },
            { key: 'MZ', title: "Mozambique" },
            { key: 'MM', title: "Myanmar" },
            { key: 'NA', title: "Namibia" },
            { key: 'NR', title: "Nauru" },
            { key: 'NP', title: "Nepal" },
            { key: 'NL', title: "Netherlands" },
            { key: 'AN', title: "Netherlands Antilles" },
            { key: 'NC', title: "New Caledonia" },
            { key: 'NZ', title: "New Zealand" },
            { key: 'NI', title: "Nicaragua" },
            { key: 'NE', title: "Niger" },
            { key: 'NG', title: "Nigeria" },
            { key: 'NU', title: "Niue" },
            { key: 'NF', title: "Norfolk Island" },
            { key: 'MP', title: "Northern Mariana Islands" },
            { key: 'NO', title: "Norway" },
            { key: 'OC', title: "Oceana" },
            { key: 'OM', title: "Oman" },
            { key: 'PK', title: "Pakistan" },
            { key: 'PW', title: "Palau" },
            { key: 'PA', title: "Panama" },
            { key: 'PG', title: "Papua New Guinea" },
            { key: 'PY', title: "Paraguay" },
            { key: 'PE', title: "Peru" },
            { key: 'PH', title: "Philippines" },
            { key: 'PN', title: "Pitcairn" },
            { key: 'PL', title: "Poland" },
            { key: 'PT', title: "Portugal" },
            { key: 'PR', title: "Puerto Rico" },
            { key: 'QA', title: "Qatar" },
            { key: 'RE', title: "Reunion" },
            { key: 'RO', title: "Romania" },
            { key: 'RU', title: "Russian Federation" },
            { key: 'RW', title: "Rwanda" },
            { key: 'KN', title: "Saint Kitts and Nevis" },
            { key: 'LC', title: "Saint Lucia" },
            { key: 'VC', title: "Saint Vincent and The Grenadines" },
            { key: 'WS', title: "Samoa" },
            { key: 'SM', title: "San Marino" },
            { key: 'ST', title: "Sao Tome and Principe" },
            { key: 'SA', title: "Saudi Arabia" },
            { key: 'SN', title: "Senegal" },
            { key: 'RS', title: "Serbia and Montenegro" },
            { key: 'SC', title: "Seychelles" },
            { key: 'SL', title: "Sierra Leone" },
            { key: 'SG', title: "Singapore" },
            { key: 'SK', title: "Slovakia (Slovak Republic)" },
            { key: 'SI', title: "Slovenia" },
            { key: 'SB', title: "Solomon Islands" },
            { key: 'SO', title: "Somalia" },
            { key: 'ZA', title: "South Africa" },
            { key: 'ES', title: "Spain" },
            { key: 'LK', title: "Sri Lanka" },
            { key: 'SH', title: "St. Helena" },
            { key: 'PM', title: "St. Pierre and Miquelon" },
            { key: 'SR', title: "Suriname" },
            { key: 'SJ', title: "Svalbard and Jan Mayen Islands" },
            { key: 'SZ', title: "Swaziland" },
            { key: 'SE', title: "Sweden" },
            { key: 'CH', title: "Switzerland" },
            { key: 'TW', title: "Taiwan" },
            { key: 'TJ', title: "Tajikistan" },
            { key: 'TZ', title: "Tanzania, United Republic of" },
            { key: 'TH', title: "Thailand" },
            { key: 'TG', title: "Togo" },
            { key: 'TK', title: "Tokelau" },
            { key: 'TO', title: "Tonga" },
            { key: 'TT', title: "Trinidad and Tobago" },
            { key: 'TN', title: "Tunisia" },
            { key: 'TR', title: "Turkey" },
            { key: 'TM', title: "Turkmenistan" },
            { key: 'TC', title: "Turks and Caicos Islands" },
            { key: 'TV', title: "Tuvalu" },
            { key: 'UM', title: "US Minor Outlying Islands" },
            { key: 'UG', title: "Uganda" },
            { key: 'UA', title: "Ukraine" },
            { key: 'AE', title: "United Arab Emirates" },
            { key: 'UK', title: "United Kingdom" },
            { key: 'US', title: "United States" },
            { key: 'UY', title: "Uruguay" },
            { key: 'UZ', title: "Uzbekistan" },
            { key: 'VU', title: "Vanuatu" },
            { key: 'VA', title: "Vatican City" },
            { key: 'VE', title: "Venezuela" },
            { key: 'VN', title: "Viet Nam" },
            { key: 'VG', title: "Virgin Islands (British)" },
            { key: 'VI', title: "Virgin Islands (U.S.)" },
            { key: 'WF', title: "Wallis and Futuna Islands" },
            { key: 'EH', title: "Western Sahara" },
            { key: 'YE', title: "Yemen" },
            { key: 'YU', title: "Yugoslavia" },
            { key: 'ZR', title: "Zaire" },
            { key: 'ZM', title: "Zambia" },
            { key: 'ZW', title: "Zimbabwe" },
        ];
    }
    Countries.prototype.get = function (country) {
        return this.countries.find(function (item) { return item.key === country; });
    };
    return Countries;
}());
exports.Countries = Countries;
//# sourceMappingURL=countries.js.map